language: php

php:
    - 7.1

install:
    - cp .env.testing .env  
    - composer self-update
    - composer install --no-interaction --prefer-dist --no-suggest

script:
    - vendor/phpunit/phpunit/phpunit
